packages:
  - src/renderer
  - plugins-doc

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - electron
  - electron-winstaller
  - esbuild
  - extract-file-icon
  - javascript-obfuscator
