packages:
  - src/renderer
  - src/libs/**

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - electron
  - electron-winstaller
  - esbuild
  - extract-file-icon
  - javascript-obfuscator
