/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppItem: typeof import('./../src/components/Search/AppItem.vue')['default']
    ContentArea: typeof import('./../src/components/ContentArea/ContentArea.vue')['default']
    ContextMenu: typeof import('./../src/components/ContextMenu/ContextMenu.vue')['default']
    DraggableArea: typeof import('./../src/components/DraggableArea/DraggableArea.vue')['default']
    DragIcon: typeof import('./../src/components/SearchHeader/DragIcon.vue')['default']
    EmptyState: typeof import('./../src/components/ContentArea/EmptyState.vue')['default']
    FileInfoDisplay: typeof import('./../src/components/SearchHeader/FileInfoDisplay.vue')['default']
    IconDisplay: typeof import('./../src/components/Common/IconDisplay.vue')['default']
    IconMdiClose: typeof import('~icons/mdi/close')['default']
    IconMdiContentCopy: typeof import('~icons/mdi/content-copy')['default']
    IconMdiDockWindow: typeof import('~icons/mdi/dock-window')['default']
    IconMdiDownload: typeof import('~icons/mdi/download')['default']
    IconMdiLoading: typeof import('~icons/mdi/loading')['default']
    IconMdiPin: typeof import('~icons/mdi/pin')['default']
    IconMdiPinOutline: typeof import('~icons/mdi/pin-outline')['default']
    IconMdiPuzzle: typeof import('~icons/mdi/puzzle')['default']
    IconMdiPuzzleOutline: typeof import('~icons/mdi/puzzle-outline')['default']
    IconMdiWindowClose: typeof import('~icons/mdi/window-close')['default']
    IconMdiWindowMaximize: typeof import('~icons/mdi/window-maximize')['default']
    IconMdiWindowMinimize: typeof import('~icons/mdi/window-minimize')['default']
    IconMdiWindowOpenVariant: typeof import('~icons/mdi/window-open-variant')['default']
    IconMdiWindowRestore: typeof import('~icons/mdi/window-restore')['default']
    LoadingSpinner: typeof import('./../src/components/Common/LoadingSpinner.vue')['default']
    PluginInfoDisplay: typeof import('./../src/components/SearchHeader/PluginInfoDisplay.vue')['default']
    PluginSettingsButton: typeof import('./../src/components/Common/PluginSettingsButton.vue')['default']
    PluginWindowPlaceholder: typeof import('./../src/components/ContentArea/PluginWindowPlaceholder.vue')['default']
    ProgressBar: typeof import('./../src/components/Common/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchCategories: typeof import('./../src/components/Search/SearchCategories.vue')['default']
    SearchHeader: typeof import('./../src/components/SearchHeader/SearchHeader.vue')['default']
    SearchInput: typeof import('./../src/components/Search/SearchInput.vue')['default']
    SettingsBackground: typeof import('./../src/components/ContentArea/SettingsBackground.vue')['default']
    SettingsButton: typeof import('./../src/components/SearchHeader/SettingsButton.vue')['default']
  }
}
